baseURL = "https://hlwilk.com/"
languageCode = "en-us"
theme = "terminal"
pagination.pagerSize = 5
relativeURLs = true

[markup.highlight]
  noClasses = false

[params]
  contentTypeName = "posts"
  showMenuItems = 4
  fullWidthTheme = false
  centerTheme = true

[languages]
  [languages.en]
    languageName = "English"
    title = "Hannah Wilk"

    [languages.en.params]
      subtitle = "VFX Artist & Photographer"

      [languages.en.params.logo]
        logoText = "Hannah Wilk"
        logoHomeLink = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "portfolio"
        name = "Portfolio"
        url = "/portfolio"
        weight = 1
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
        weight = 2
      [[languages.en.menu.main]]
        identifier = "posts"
        name = "Posts"
        url = "/posts"
        weight = 3